version: '3.8'

services:
  prometeus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    depends_on:
      - prometeus

  nginx_with_node_exporter_like_vm:
    container_name: nginx
    hostname: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "9101:9100"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
   
  nginx-exporter1:
    image: nginx/nginx-prometheus-exporter:1.1.0
    ports:
      - "9113:9113"
    command: "--nginx.scrape-uri=http://nginx:8080/stub_status"

